import React from "react";
import ReactDOM from "react-dom";
import { TodoApp } from "./components/08-useReducer/TodoApp";
//import { MainApp } from "./components/09-useContext/MainApp";
//import { PrincipalRouter } from "./Routes/PrincipalRouter";
//import { CallbackHook } from "./components/06-Memo/CallbackHook";
//import { Padre } from "./components/07-tarea-memo/Padre";
//import { MemoHook } from "./components/06-Memo/MemoHook";
//import { LayoutEffect } from "./components/05-UseLayOutEffect/LayoutEffect";
//import { Memorize } from "./components/06-Memo/Memorize";
//import { FocusScreen } from "./components/04-useRef/FocusScreen";
//import { RealExampleRef } from "./components/04-useRef/RealExampleRef";
//import { FormWithCustomHook } from "./components/02-useEffect/FormWithCustomHook";
//import { MultipleCustomHooks } from "./components/examples/MultipleCustomHooks";
//import { SimpleForm } from "./components/02-useEffect/SimpleForm";
//import { CounterApp } from "./components/01-useState/CounterApp";
//import { CounterWithCustomHook } from "./components/01-useState/CounterWithCustomHook";
//import { HooksApp } from "./HooksApp";

ReactDOM.render(<TodoApp />, document.getElementById("root"));
